-- Synthetic disposable data only; never use actual bookings/receipts.
INSERT INTO hotel_tenants(id,n3_tenant_key) VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','synthetic-tenant-a'),('99999999-9999-4999-8999-999999999999','synthetic-tenant-b');
INSERT INTO hotel_user_roles(tenant_id,n3_user_key,role) VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','synthetic-owner','owner');
INSERT INTO hotel_booking_sources(tenant_id,source_code,display_name) VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','walk_in','Synthetic') ON CONFLICT(tenant_id,source_code) DO NOTHING;
INSERT INTO hotel_reservations(id,tenant_id,booking_reference,booking_source,status,arrival_date,departure_date,currency,created_by_n3_user_key)
VALUES ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','SYNTHETIC-ONE','walk_in','checked_in','2026-10-07','2026-10-09','MYR','synthetic-owner'),
('88888888-8888-4888-8888-888888888888','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','SYNTHETIC-TWO','walk_in','checked_in','2026-10-07','2026-10-09','MYR','synthetic-owner');
INSERT INTO hotel_folios(id,tenant_id,reservation_id,status) VALUES ('cccccccc-cccc-4ccc-8ccc-cccccccccccc','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','prepared'),('77777777-7777-4777-8777-777777777777','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','88888888-8888-4888-8888-888888888888','prepared');
INSERT INTO hotel_folio_lines(id,tenant_id,folio_id,line_type,description_snapshot,unit_price_cents,subtotal_cents,total_cents,actor_n3_user_key)
VALUES ('dddddddd-dddd-4ddd-8ddd-dddddddddddd','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','cccccccc-cccc-4ccc-8ccc-cccccccccccc','add_on','Synthetic charge',50000,50000,50000,'synthetic-owner');
INSERT INTO hotel_folio_bill_to(tenant_id,reservation_id,name) VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','Synthetic guest');
INSERT INTO hotel_reservation_tax_profile(tenant_id,reservation_id) VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb');
INSERT INTO hotel_reservation_deposits(id,tenant_id,reservation_id,amount,currency_code,idempotency_key,n3_reference_no,status,created_by_n3_user_key) VALUES ('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',50,'MYR','synthetic-deposit','SYNTHETIC-DEP','failed','synthetic-owner');
INSERT INTO hotel_receipt_control_requests(id,tenant_id,reservation_id,deposit_id,client_request_id,request_fingerprint,kind,reason,original,proposal,comparison,original_amount_cents,proposed_amount_cents,state,requested_by_n3_user_key) VALUES ('66666666-6666-4666-8666-666666666666','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',gen_random_uuid(),repeat('a',64),'correction','Synthetic reason','{}','{}','{}',5000,6000,'rejected','synthetic-owner');
INSERT INTO hotel_reservation_operation_requests(id,tenant_id,reservation_id,operation_type,state,requested_by_n3_user_key,decided_by_n3_user_key,decided_at,idempotency_key) VALUES ('55555555-5555-4555-8555-555555555555','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','late_checkout','rejected','synthetic-owner','synthetic-owner',now(),'synthetic-operation');
