/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoomsRatesRouteImport } from './routes/rooms-rates'
import { Route as LaunchErrorRouteImport } from './routes/launch-error'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservationsIndexRouteImport } from './routes/reservations.index'
import { Route as ReservationsNewRouteImport } from './routes/reservations.new'
import { Route as ReservationsCalendarRouteImport } from './routes/reservations.calendar'
import { Route as ReservationsIdRouteImport } from './routes/reservations.$id'
import { Route as ReservationsIdPrintRouteImport } from './routes/reservations.$id_.print'
import { Route as ApiSessionMeRouteImport } from './routes/api/session/me'
import { Route as ApiN3StocksRouteImport } from './routes/api/n3/stocks'
import { Route as ApiN3CustomersRouteImport } from './routes/api/n3/customers'
import { Route as ApiHotelWalkInCustomerRouteImport } from './routes/api/hotel/walk-in-customer'
import { Route as ApiHotelSettingsRouteImport } from './routes/api/hotel/settings'
import { Route as ApiHotelRoomsRouteImport } from './routes/api/hotel/rooms'
import { Route as ApiHotelReservationsRouteImport } from './routes/api/hotel/reservations'
import { Route as ApiHotelReservationCalendarRouteImport } from './routes/api/hotel/reservation-calendar'
import { Route as ApiHotelBookingSourcesRouteImport } from './routes/api/hotel/booking-sources'
import { Route as ApiHotelAvailabilityRouteImport } from './routes/api/hotel/availability'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLaunchRouteImport } from './routes/api/auth/launch'
import { Route as ApiAuthConnectRouteImport } from './routes/api/auth/connect'
import { Route as ApiN3ProbeIndexRouteImport } from './routes/api/n3/probe/index'
import { Route as ApiN3StocksAllRouteImport } from './routes/api/n3/stocks.all'
import { Route as ApiN3ProbeProbeRouteImport } from './routes/api/n3/probe/$probe'
import { Route as ApiN3CustomersAllRouteImport } from './routes/api/n3/customers.all'
import { Route as ApiHotelRoomsIdRouteImport } from './routes/api/hotel/rooms.$id'
import { Route as ApiHotelReservationsIdRouteImport } from './routes/api/hotel/reservations.$id'
import { Route as ApiHotelBookingSourcesIdRouteImport } from './routes/api/hotel/booking-sources.$id'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRatesRoute = RoomsRatesRouteImport.update({
  id: '/rooms-rates',
  path: '/rooms-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchErrorRoute = LaunchErrorRouteImport.update({
  id: '/launch-error',
  path: '/launch-error',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsIndexRoute = ReservationsIndexRouteImport.update({
  id: '/reservations/',
  path: '/reservations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsNewRoute = ReservationsNewRouteImport.update({
  id: '/reservations/new',
  path: '/reservations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsCalendarRoute = ReservationsCalendarRouteImport.update({
  id: '/reservations/calendar',
  path: '/reservations/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsIdRoute = ReservationsIdRouteImport.update({
  id: '/reservations/$id',
  path: '/reservations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsIdPrintRoute = ReservationsIdPrintRouteImport.update({
  id: '/reservations/$id_/print',
  path: '/reservations/$id/print',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionMeRoute = ApiSessionMeRouteImport.update({
  id: '/api/session/me',
  path: '/api/session/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN3StocksRoute = ApiN3StocksRouteImport.update({
  id: '/api/n3/stocks',
  path: '/api/n3/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN3CustomersRoute = ApiN3CustomersRouteImport.update({
  id: '/api/n3/customers',
  path: '/api/n3/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotelWalkInCustomerRoute = ApiHotelWalkInCustomerRouteImport.update({
  id: '/api/hotel/walk-in-customer',
  path: '/api/hotel/walk-in-customer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotelSettingsRoute = ApiHotelSettingsRouteImport.update({
  id: '/api/hotel/settings',
  path: '/api/hotel/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotelRoomsRoute = ApiHotelRoomsRouteImport.update({
  id: '/api/hotel/rooms',
  path: '/api/hotel/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotelReservationsRoute = ApiHotelReservationsRouteImport.update({
  id: '/api/hotel/reservations',
  path: '/api/hotel/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotelReservationCalendarRoute =
  ApiHotelReservationCalendarRouteImport.update({
    id: '/api/hotel/reservation-calendar',
    path: '/api/hotel/reservation-calendar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHotelBookingSourcesRoute = ApiHotelBookingSourcesRouteImport.update({
  id: '/api/hotel/booking-sources',
  path: '/api/hotel/booking-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotelAvailabilityRoute = ApiHotelAvailabilityRouteImport.update({
  id: '/api/hotel/availability',
  path: '/api/hotel/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLaunchRoute = ApiAuthLaunchRouteImport.update({
  id: '/api/auth/launch',
  path: '/api/auth/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthConnectRoute = ApiAuthConnectRouteImport.update({
  id: '/api/auth/connect',
  path: '/api/auth/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN3ProbeIndexRoute = ApiN3ProbeIndexRouteImport.update({
  id: '/api/n3/probe/',
  path: '/api/n3/probe/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN3StocksAllRoute = ApiN3StocksAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => ApiN3StocksRoute,
} as any)
const ApiN3ProbeProbeRoute = ApiN3ProbeProbeRouteImport.update({
  id: '/api/n3/probe/$probe',
  path: '/api/n3/probe/$probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN3CustomersAllRoute = ApiN3CustomersAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => ApiN3CustomersRoute,
} as any)
const ApiHotelRoomsIdRoute = ApiHotelRoomsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiHotelRoomsRoute,
} as any)
const ApiHotelReservationsIdRoute = ApiHotelReservationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiHotelReservationsRoute,
} as any)
const ApiHotelBookingSourcesIdRoute =
  ApiHotelBookingSourcesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiHotelBookingSourcesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/launch-error': typeof LaunchErrorRoute
  '/rooms-rates': typeof RoomsRatesRoute
  '/settings': typeof SettingsRoute
  '/verification': typeof VerificationRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/reservations/calendar': typeof ReservationsCalendarRoute
  '/reservations/new': typeof ReservationsNewRoute
  '/reservations/': typeof ReservationsIndexRoute
  '/api/auth/connect': typeof ApiAuthConnectRoute
  '/api/auth/launch': typeof ApiAuthLaunchRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/hotel/availability': typeof ApiHotelAvailabilityRoute
  '/api/hotel/booking-sources': typeof ApiHotelBookingSourcesRouteWithChildren
  '/api/hotel/reservation-calendar': typeof ApiHotelReservationCalendarRoute
  '/api/hotel/reservations': typeof ApiHotelReservationsRouteWithChildren
  '/api/hotel/rooms': typeof ApiHotelRoomsRouteWithChildren
  '/api/hotel/settings': typeof ApiHotelSettingsRoute
  '/api/hotel/walk-in-customer': typeof ApiHotelWalkInCustomerRoute
  '/api/n3/customers': typeof ApiN3CustomersRouteWithChildren
  '/api/n3/stocks': typeof ApiN3StocksRouteWithChildren
  '/api/session/me': typeof ApiSessionMeRoute
  '/reservations/$id/print': typeof ReservationsIdPrintRoute
  '/api/hotel/booking-sources/$id': typeof ApiHotelBookingSourcesIdRoute
  '/api/hotel/reservations/$id': typeof ApiHotelReservationsIdRoute
  '/api/hotel/rooms/$id': typeof ApiHotelRoomsIdRoute
  '/api/n3/customers/all': typeof ApiN3CustomersAllRoute
  '/api/n3/probe/$probe': typeof ApiN3ProbeProbeRoute
  '/api/n3/stocks/all': typeof ApiN3StocksAllRoute
  '/api/n3/probe/': typeof ApiN3ProbeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/launch-error': typeof LaunchErrorRoute
  '/rooms-rates': typeof RoomsRatesRoute
  '/settings': typeof SettingsRoute
  '/verification': typeof VerificationRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/reservations/calendar': typeof ReservationsCalendarRoute
  '/reservations/new': typeof ReservationsNewRoute
  '/reservations': typeof ReservationsIndexRoute
  '/api/auth/connect': typeof ApiAuthConnectRoute
  '/api/auth/launch': typeof ApiAuthLaunchRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/hotel/availability': typeof ApiHotelAvailabilityRoute
  '/api/hotel/booking-sources': typeof ApiHotelBookingSourcesRouteWithChildren
  '/api/hotel/reservation-calendar': typeof ApiHotelReservationCalendarRoute
  '/api/hotel/reservations': typeof ApiHotelReservationsRouteWithChildren
  '/api/hotel/rooms': typeof ApiHotelRoomsRouteWithChildren
  '/api/hotel/settings': typeof ApiHotelSettingsRoute
  '/api/hotel/walk-in-customer': typeof ApiHotelWalkInCustomerRoute
  '/api/n3/customers': typeof ApiN3CustomersRouteWithChildren
  '/api/n3/stocks': typeof ApiN3StocksRouteWithChildren
  '/api/session/me': typeof ApiSessionMeRoute
  '/reservations/$id/print': typeof ReservationsIdPrintRoute
  '/api/hotel/booking-sources/$id': typeof ApiHotelBookingSourcesIdRoute
  '/api/hotel/reservations/$id': typeof ApiHotelReservationsIdRoute
  '/api/hotel/rooms/$id': typeof ApiHotelRoomsIdRoute
  '/api/n3/customers/all': typeof ApiN3CustomersAllRoute
  '/api/n3/probe/$probe': typeof ApiN3ProbeProbeRoute
  '/api/n3/stocks/all': typeof ApiN3StocksAllRoute
  '/api/n3/probe': typeof ApiN3ProbeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/launch-error': typeof LaunchErrorRoute
  '/rooms-rates': typeof RoomsRatesRoute
  '/settings': typeof SettingsRoute
  '/verification': typeof VerificationRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/reservations/calendar': typeof ReservationsCalendarRoute
  '/reservations/new': typeof ReservationsNewRoute
  '/reservations/': typeof ReservationsIndexRoute
  '/api/auth/connect': typeof ApiAuthConnectRoute
  '/api/auth/launch': typeof ApiAuthLaunchRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/hotel/availability': typeof ApiHotelAvailabilityRoute
  '/api/hotel/booking-sources': typeof ApiHotelBookingSourcesRouteWithChildren
  '/api/hotel/reservation-calendar': typeof ApiHotelReservationCalendarRoute
  '/api/hotel/reservations': typeof ApiHotelReservationsRouteWithChildren
  '/api/hotel/rooms': typeof ApiHotelRoomsRouteWithChildren
  '/api/hotel/settings': typeof ApiHotelSettingsRoute
  '/api/hotel/walk-in-customer': typeof ApiHotelWalkInCustomerRoute
  '/api/n3/customers': typeof ApiN3CustomersRouteWithChildren
  '/api/n3/stocks': typeof ApiN3StocksRouteWithChildren
  '/api/session/me': typeof ApiSessionMeRoute
  '/reservations/$id_/print': typeof ReservationsIdPrintRoute
  '/api/hotel/booking-sources/$id': typeof ApiHotelBookingSourcesIdRoute
  '/api/hotel/reservations/$id': typeof ApiHotelReservationsIdRoute
  '/api/hotel/rooms/$id': typeof ApiHotelRoomsIdRoute
  '/api/n3/customers/all': typeof ApiN3CustomersAllRoute
  '/api/n3/probe/$probe': typeof ApiN3ProbeProbeRoute
  '/api/n3/stocks/all': typeof ApiN3StocksAllRoute
  '/api/n3/probe/': typeof ApiN3ProbeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/launch-error'
    | '/rooms-rates'
    | '/settings'
    | '/verification'
    | '/reservations/$id'
    | '/reservations/calendar'
    | '/reservations/new'
    | '/reservations/'
    | '/api/auth/connect'
    | '/api/auth/launch'
    | '/api/auth/logout'
    | '/api/hotel/availability'
    | '/api/hotel/booking-sources'
    | '/api/hotel/reservation-calendar'
    | '/api/hotel/reservations'
    | '/api/hotel/rooms'
    | '/api/hotel/settings'
    | '/api/hotel/walk-in-customer'
    | '/api/n3/customers'
    | '/api/n3/stocks'
    | '/api/session/me'
    | '/reservations/$id/print'
    | '/api/hotel/booking-sources/$id'
    | '/api/hotel/reservations/$id'
    | '/api/hotel/rooms/$id'
    | '/api/n3/customers/all'
    | '/api/n3/probe/$probe'
    | '/api/n3/stocks/all'
    | '/api/n3/probe/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/launch-error'
    | '/rooms-rates'
    | '/settings'
    | '/verification'
    | '/reservations/$id'
    | '/reservations/calendar'
    | '/reservations/new'
    | '/reservations'
    | '/api/auth/connect'
    | '/api/auth/launch'
    | '/api/auth/logout'
    | '/api/hotel/availability'
    | '/api/hotel/booking-sources'
    | '/api/hotel/reservation-calendar'
    | '/api/hotel/reservations'
    | '/api/hotel/rooms'
    | '/api/hotel/settings'
    | '/api/hotel/walk-in-customer'
    | '/api/n3/customers'
    | '/api/n3/stocks'
    | '/api/session/me'
    | '/reservations/$id/print'
    | '/api/hotel/booking-sources/$id'
    | '/api/hotel/reservations/$id'
    | '/api/hotel/rooms/$id'
    | '/api/n3/customers/all'
    | '/api/n3/probe/$probe'
    | '/api/n3/stocks/all'
    | '/api/n3/probe'
  id:
    | '__root__'
    | '/'
    | '/launch-error'
    | '/rooms-rates'
    | '/settings'
    | '/verification'
    | '/reservations/$id'
    | '/reservations/calendar'
    | '/reservations/new'
    | '/reservations/'
    | '/api/auth/connect'
    | '/api/auth/launch'
    | '/api/auth/logout'
    | '/api/hotel/availability'
    | '/api/hotel/booking-sources'
    | '/api/hotel/reservation-calendar'
    | '/api/hotel/reservations'
    | '/api/hotel/rooms'
    | '/api/hotel/settings'
    | '/api/hotel/walk-in-customer'
    | '/api/n3/customers'
    | '/api/n3/stocks'
    | '/api/session/me'
    | '/reservations/$id_/print'
    | '/api/hotel/booking-sources/$id'
    | '/api/hotel/reservations/$id'
    | '/api/hotel/rooms/$id'
    | '/api/n3/customers/all'
    | '/api/n3/probe/$probe'
    | '/api/n3/stocks/all'
    | '/api/n3/probe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LaunchErrorRoute: typeof LaunchErrorRoute
  RoomsRatesRoute: typeof RoomsRatesRoute
  SettingsRoute: typeof SettingsRoute
  VerificationRoute: typeof VerificationRoute
  ReservationsIdRoute: typeof ReservationsIdRoute
  ReservationsCalendarRoute: typeof ReservationsCalendarRoute
  ReservationsNewRoute: typeof ReservationsNewRoute
  ReservationsIndexRoute: typeof ReservationsIndexRoute
  ApiAuthConnectRoute: typeof ApiAuthConnectRoute
  ApiAuthLaunchRoute: typeof ApiAuthLaunchRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiHotelAvailabilityRoute: typeof ApiHotelAvailabilityRoute
  ApiHotelBookingSourcesRoute: typeof ApiHotelBookingSourcesRouteWithChildren
  ApiHotelReservationCalendarRoute: typeof ApiHotelReservationCalendarRoute
  ApiHotelReservationsRoute: typeof ApiHotelReservationsRouteWithChildren
  ApiHotelRoomsRoute: typeof ApiHotelRoomsRouteWithChildren
  ApiHotelSettingsRoute: typeof ApiHotelSettingsRoute
  ApiHotelWalkInCustomerRoute: typeof ApiHotelWalkInCustomerRoute
  ApiN3CustomersRoute: typeof ApiN3CustomersRouteWithChildren
  ApiN3StocksRoute: typeof ApiN3StocksRouteWithChildren
  ApiSessionMeRoute: typeof ApiSessionMeRoute
  ReservationsIdPrintRoute: typeof ReservationsIdPrintRoute
  ApiN3ProbeProbeRoute: typeof ApiN3ProbeProbeRoute
  ApiN3ProbeIndexRoute: typeof ApiN3ProbeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms-rates': {
      id: '/rooms-rates'
      path: '/rooms-rates'
      fullPath: '/rooms-rates'
      preLoaderRoute: typeof RoomsRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch-error': {
      id: '/launch-error'
      path: '/launch-error'
      fullPath: '/launch-error'
      preLoaderRoute: typeof LaunchErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/': {
      id: '/reservations/'
      path: '/reservations'
      fullPath: '/reservations/'
      preLoaderRoute: typeof ReservationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/new': {
      id: '/reservations/new'
      path: '/reservations/new'
      fullPath: '/reservations/new'
      preLoaderRoute: typeof ReservationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/calendar': {
      id: '/reservations/calendar'
      path: '/reservations/calendar'
      fullPath: '/reservations/calendar'
      preLoaderRoute: typeof ReservationsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/$id': {
      id: '/reservations/$id'
      path: '/reservations/$id'
      fullPath: '/reservations/$id'
      preLoaderRoute: typeof ReservationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/$id_/print': {
      id: '/reservations/$id_/print'
      path: '/reservations/$id/print'
      fullPath: '/reservations/$id/print'
      preLoaderRoute: typeof ReservationsIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session/me': {
      id: '/api/session/me'
      path: '/api/session/me'
      fullPath: '/api/session/me'
      preLoaderRoute: typeof ApiSessionMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n3/stocks': {
      id: '/api/n3/stocks'
      path: '/api/n3/stocks'
      fullPath: '/api/n3/stocks'
      preLoaderRoute: typeof ApiN3StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n3/customers': {
      id: '/api/n3/customers'
      path: '/api/n3/customers'
      fullPath: '/api/n3/customers'
      preLoaderRoute: typeof ApiN3CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotel/walk-in-customer': {
      id: '/api/hotel/walk-in-customer'
      path: '/api/hotel/walk-in-customer'
      fullPath: '/api/hotel/walk-in-customer'
      preLoaderRoute: typeof ApiHotelWalkInCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotel/settings': {
      id: '/api/hotel/settings'
      path: '/api/hotel/settings'
      fullPath: '/api/hotel/settings'
      preLoaderRoute: typeof ApiHotelSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotel/rooms': {
      id: '/api/hotel/rooms'
      path: '/api/hotel/rooms'
      fullPath: '/api/hotel/rooms'
      preLoaderRoute: typeof ApiHotelRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotel/reservations': {
      id: '/api/hotel/reservations'
      path: '/api/hotel/reservations'
      fullPath: '/api/hotel/reservations'
      preLoaderRoute: typeof ApiHotelReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotel/reservation-calendar': {
      id: '/api/hotel/reservation-calendar'
      path: '/api/hotel/reservation-calendar'
      fullPath: '/api/hotel/reservation-calendar'
      preLoaderRoute: typeof ApiHotelReservationCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotel/booking-sources': {
      id: '/api/hotel/booking-sources'
      path: '/api/hotel/booking-sources'
      fullPath: '/api/hotel/booking-sources'
      preLoaderRoute: typeof ApiHotelBookingSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotel/availability': {
      id: '/api/hotel/availability'
      path: '/api/hotel/availability'
      fullPath: '/api/hotel/availability'
      preLoaderRoute: typeof ApiHotelAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/launch': {
      id: '/api/auth/launch'
      path: '/api/auth/launch'
      fullPath: '/api/auth/launch'
      preLoaderRoute: typeof ApiAuthLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/connect': {
      id: '/api/auth/connect'
      path: '/api/auth/connect'
      fullPath: '/api/auth/connect'
      preLoaderRoute: typeof ApiAuthConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n3/probe/': {
      id: '/api/n3/probe/'
      path: '/api/n3/probe'
      fullPath: '/api/n3/probe/'
      preLoaderRoute: typeof ApiN3ProbeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n3/stocks/all': {
      id: '/api/n3/stocks/all'
      path: '/all'
      fullPath: '/api/n3/stocks/all'
      preLoaderRoute: typeof ApiN3StocksAllRouteImport
      parentRoute: typeof ApiN3StocksRoute
    }
    '/api/n3/probe/$probe': {
      id: '/api/n3/probe/$probe'
      path: '/api/n3/probe/$probe'
      fullPath: '/api/n3/probe/$probe'
      preLoaderRoute: typeof ApiN3ProbeProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n3/customers/all': {
      id: '/api/n3/customers/all'
      path: '/all'
      fullPath: '/api/n3/customers/all'
      preLoaderRoute: typeof ApiN3CustomersAllRouteImport
      parentRoute: typeof ApiN3CustomersRoute
    }
    '/api/hotel/rooms/$id': {
      id: '/api/hotel/rooms/$id'
      path: '/$id'
      fullPath: '/api/hotel/rooms/$id'
      preLoaderRoute: typeof ApiHotelRoomsIdRouteImport
      parentRoute: typeof ApiHotelRoomsRoute
    }
    '/api/hotel/reservations/$id': {
      id: '/api/hotel/reservations/$id'
      path: '/$id'
      fullPath: '/api/hotel/reservations/$id'
      preLoaderRoute: typeof ApiHotelReservationsIdRouteImport
      parentRoute: typeof ApiHotelReservationsRoute
    }
    '/api/hotel/booking-sources/$id': {
      id: '/api/hotel/booking-sources/$id'
      path: '/$id'
      fullPath: '/api/hotel/booking-sources/$id'
      preLoaderRoute: typeof ApiHotelBookingSourcesIdRouteImport
      parentRoute: typeof ApiHotelBookingSourcesRoute
    }
  }
}

interface ApiHotelBookingSourcesRouteChildren {
  ApiHotelBookingSourcesIdRoute: typeof ApiHotelBookingSourcesIdRoute
}

const ApiHotelBookingSourcesRouteChildren: ApiHotelBookingSourcesRouteChildren =
  {
    ApiHotelBookingSourcesIdRoute: ApiHotelBookingSourcesIdRoute,
  }

const ApiHotelBookingSourcesRouteWithChildren =
  ApiHotelBookingSourcesRoute._addFileChildren(
    ApiHotelBookingSourcesRouteChildren,
  )

interface ApiHotelReservationsRouteChildren {
  ApiHotelReservationsIdRoute: typeof ApiHotelReservationsIdRoute
}

const ApiHotelReservationsRouteChildren: ApiHotelReservationsRouteChildren = {
  ApiHotelReservationsIdRoute: ApiHotelReservationsIdRoute,
}

const ApiHotelReservationsRouteWithChildren =
  ApiHotelReservationsRoute._addFileChildren(ApiHotelReservationsRouteChildren)

interface ApiHotelRoomsRouteChildren {
  ApiHotelRoomsIdRoute: typeof ApiHotelRoomsIdRoute
}

const ApiHotelRoomsRouteChildren: ApiHotelRoomsRouteChildren = {
  ApiHotelRoomsIdRoute: ApiHotelRoomsIdRoute,
}

const ApiHotelRoomsRouteWithChildren = ApiHotelRoomsRoute._addFileChildren(
  ApiHotelRoomsRouteChildren,
)

interface ApiN3CustomersRouteChildren {
  ApiN3CustomersAllRoute: typeof ApiN3CustomersAllRoute
}

const ApiN3CustomersRouteChildren: ApiN3CustomersRouteChildren = {
  ApiN3CustomersAllRoute: ApiN3CustomersAllRoute,
}

const ApiN3CustomersRouteWithChildren = ApiN3CustomersRoute._addFileChildren(
  ApiN3CustomersRouteChildren,
)

interface ApiN3StocksRouteChildren {
  ApiN3StocksAllRoute: typeof ApiN3StocksAllRoute
}

const ApiN3StocksRouteChildren: ApiN3StocksRouteChildren = {
  ApiN3StocksAllRoute: ApiN3StocksAllRoute,
}

const ApiN3StocksRouteWithChildren = ApiN3StocksRoute._addFileChildren(
  ApiN3StocksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LaunchErrorRoute: LaunchErrorRoute,
  RoomsRatesRoute: RoomsRatesRoute,
  SettingsRoute: SettingsRoute,
  VerificationRoute: VerificationRoute,
  ReservationsIdRoute: ReservationsIdRoute,
  ReservationsCalendarRoute: ReservationsCalendarRoute,
  ReservationsNewRoute: ReservationsNewRoute,
  ReservationsIndexRoute: ReservationsIndexRoute,
  ApiAuthConnectRoute: ApiAuthConnectRoute,
  ApiAuthLaunchRoute: ApiAuthLaunchRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiHotelAvailabilityRoute: ApiHotelAvailabilityRoute,
  ApiHotelBookingSourcesRoute: ApiHotelBookingSourcesRouteWithChildren,
  ApiHotelReservationCalendarRoute: ApiHotelReservationCalendarRoute,
  ApiHotelReservationsRoute: ApiHotelReservationsRouteWithChildren,
  ApiHotelRoomsRoute: ApiHotelRoomsRouteWithChildren,
  ApiHotelSettingsRoute: ApiHotelSettingsRoute,
  ApiHotelWalkInCustomerRoute: ApiHotelWalkInCustomerRoute,
  ApiN3CustomersRoute: ApiN3CustomersRouteWithChildren,
  ApiN3StocksRoute: ApiN3StocksRouteWithChildren,
  ApiSessionMeRoute: ApiSessionMeRoute,
  ReservationsIdPrintRoute: ReservationsIdPrintRoute,
  ApiN3ProbeProbeRoute: ApiN3ProbeProbeRoute,
  ApiN3ProbeIndexRoute: ApiN3ProbeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
